"""Craete fields voice comment, file_med_procedure

Revision ID: 27653de3141e
Revises: 5761a3ec8205
Create Date: 2025-06-14 11:30:36.325757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27653de3141e"
down_revision: Union[str, None] = "5761a3ec8205"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "med_procedures", sa.Column("voice_comment", sa.String(), nullable=True)
    )
    op.add_column(
        "med_procedures", sa.Column("file_med_procedure", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("med_procedures", "file_med_procedure")
    op.drop_column("med_procedures", "voice_comment")
    # ### end Alembic commands ###
